stages:
    - test

unit_tests:
    stage: test
    script:
        - ./bin/build-helper version
        - ./bin/build-helper test

pycodestyle:
    stage: test
    script:
        - $(command -v pycodestyle3)
        - $(command -v pycodestyle)
        - ls -l $(command -v pycodestyle)
        - ./bin/build-helper pycodestyle

shellcheck:
    stage: test
    script:
        - ./bin/build-helper shellcheck
